Update determine_environment.yml

diff --git a/.github/workflows/determine_environment.yml b/.github/workflows/determine_environment.yml
--- a/.github/workflows/determine_environment.yml
+++ b/.github/workflows/determine_environment.yml
@@ -36,6 +36,9 @@ jobs:
           elif [[ "${{ github.ref }}" == "refs/heads/testing" ]]; then
             ENVIRONMENT_NAME="testing"
             ENVIRONMENT_NAME_NORMALIZED="Testing"
+          else
+            echo "Environment name could not be determined"
+            exit 1
           fi
           
           # Set outputs
